#!/usr/bin/env bash

set -e
set -o pipefail

TASK=$1
ARGS=${@:2}

runs_inside_gocd() {
  test -n "${GO_JOB_NAME}"
}

help__startserver="start server"
task_startserver() {
  uvicorn app.main:app --reload --host=0.0.0.0 --port=${PORT:-5000}
}

## main

list_all_helps() {
  compgen -v | egrep "^help__.*"
}

NEW_LINE=$'\n'
if type -t "task_$TASK" &>/dev/null; then
  task_${TASK} ${ARGS}
else
  echo "usage: $0 <task> [<..args>]"
  echo "task:"

  HELPS=""
  for help in $(list_all_helps)
  do

    HELPS="$HELPS    ${help/help__/} |-- ${!help}$NEW_LINE"
  done

  echo "$HELPS" | column -t -s "|"
  exit 1
fi
